on:
  workflow_call:
    inputs:
      is-pr:
        required: false
        type: boolean

jobs:
  buildAndTest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 7.0.*
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0
        with:
          versionSpec: '6.x'
          preferLatestVersion: true
          includePrerelease: true
      - name: Determine Version
        id: version
        uses: gittools/actions/gitversion/execute@v0
        with:
          useConfigFile: true
      - name: Install Dependencies
        run: dotnet restore ./Lewee.sln --nologo
      - name: Build
        run: dotnet build ./Lewee.sln --configuration Release --no-restore --nologo
      - name: Test
        run: dotnet test ./Lewee.sln --configuration Release --no-build --nologo --settings coverage.runsettings --results-directory ./coverage
      - name: Code Coverage Report
        uses: irongut/CodeCoverageSummary@v1.3.0
        if: ${{ inputs.is-pr == true }}
        with:
          filename: coverage/**/coverage.cobertura.xml
          badge: true
          format: markdown
          hide_branch_rate: false
          hide_complexity: false
          indicators: true
          output: both
          
      #- name: Add Coverage PR Comment
      #  uses: marocchino/sticky-pull-request-comment@v2
      #  if: ${{ inputs.is-pr == true }}
      #  with:
      #    recreate: true
      #    path: code-coverage-results.md
          
      - name: Pack
        run: dotnet pack ./Lewee.sln --configuration Release --nologo /p:PackageVersion=${{ steps.version.outputs.fullSemVer }} --output ./output
      - name: Publish to NuGet
        run: dotnet nuget push ./output/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate
        if: github.ref == 'refs/heads/main'
